// Generated by CoffeeScript 1.8.0
var FooView, KDView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

KDView = require('kdf-view');

FooView = (function(_super) {
  __extends(FooView, _super);

  function FooView(options, data) {
    if (options == null) {
      options = {};
    }
    FooView.__super__.constructor.call(this, options, data);
    this.barView = new KDView({
      pistachio: "<div>BAR!</div>"
    });
  }

  FooView.prototype.pistachio = function() {
    return "<section class=\"foo\">\n  {{> @barView}}\n</section>";
  };

  return FooView;

})(KDView);
